project:
  type: book

book:
  title: "Proyecto Reinforcement Learning"
  author: "José Ítalo Sánchez Bermúdez"
  date: "26/9/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - formulacion.qmd
    - modelo.qmd
    - descripcion.qmd
    - justificacion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lux
  pdf:
    documentclass: scrreprt




